DROP TABLE IF EXISTS users;

CREATE TABLE
  users (
    ID INT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(58) NOT NULL
  );

INSERT INTO
  users (ID, FIRST_NAME, LAST_NAME)
VALUES
  (1, 'John', 'Doe');

INSERT INTO
  users (ID, FIRST_NAME, LAST_NAME)
VALUES
  (2, 'Alice', 'Wonderland');